---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "registry-operator.fullname" . }}
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "registry-operator.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "registry-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "registry-operator.fullname" . }}
  secretName: {{ include "registry-operator.fullname" . }}-cert

