apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "registry-operator.fullname" . }}
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials/finalizers
  verbs:
  - update
- apiGroups:
  - registry.astrokube.com
  resources:
  - ecrcredentials/status
  verbs:
  - get
  - patch
  - update
