apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "registry-operator.fullname" . }}
  name: {{ include "registry-operator.fullname" . }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "registry-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-registry-astrokube-com-v1alpha1-ecrcredentials
  failurePolicy: Fail
  name: vecrcredentials.kb.io
  rules:
  - apiGroups:
    - registry.astrokube.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ecrcredentials
  sideEffects: None
