apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "registry-operator.fullname" . }}
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}

